[tool.poetry]
name = "jaffle-shop-classic"
version = "0.1.0"
description = ""
authors = ["Gustavo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
dbt-duckdb = "^1.8.2"
duckdb = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
